updated admin retreats table
Summ-Technologies/flok pull request #123
Opened 2022-04-06 20:31 UTC by abusel

#### Linear 🎫 
https://linear.app/flok/issue/FLO-288

##### Description
updated fields in retreats table for admin 
##### Demo
<img width="1512" alt="Screen Shot 2022-04-06 at 4 16 23 PM" src="https://user-images.githubusercontent.com/41205015/162065472-8075e0c4-2ef5-49a4-9860-942338b8a934.png">

2022-04-06 23:30 UTC, jaredhanson11 requested changes
make sure to keep our frontend models properly matching our backend models. you need to remove the flok_admin_state and flok_admin_owner and guid from these models since we removed them from the backend models as well. additionally, let's remove the unused fields from the RetreatsTableRow type so that we don't have unused code in our systems.

2022-04-06 23:31 UTC, jaredhanson11 commented
@abusel take a look at the comments and please adjust accordingly.

2022-04-07 14:45 UTC, abusel commented
My mistake, I think I already removed guid but forgot to remove flok state and owner.  Should be all fixed now

2022-04-07 20:00 UTC, jaredhanson11 approved these changes

2022-04-07 20:00 UTC, merged