Andrew/create landing pages
Summ-Technologies/flok pull request #152
Opened 2022-05-11 20:35 UTC by abusel

#### Linear 🎫 
https://linear.app/flok/issue/FLO-

##### Description
Initial version of landing page generator and website

##### Demo
<img width="1512" alt="Screen Shot 2022-05-11 at 4 34 54 PM" src="https://user-images.githubusercontent.com/41205015/167943035-ae8908d3-e7a4-40db-afe3-a3c85e76aae7.png">
<img width="1512" alt="Screen Shot 2022-05-11 at 4 34 24 PM" src="https://user-images.githubusercontent.com/41205015/167943080-e58bfd2b-470c-42fa-9e42-95e7cb31c750.png">

2022-05-12 07:39 UTC, jaredhanson11 requested changes
see changes requested

2022-05-12 07:39 UTC, jaredhanson11 commented on modules/flok/src/components/retreat-website/RetreatWebsiteHeader.tsx
> +            <Button
make this button `size=small` or it might be compact can't remember the actual value. but make it smaller pls not the default

2022-05-12 07:39 UTC, jaredhanson11 commented on modules/flok/src/components/retreat-website/RetreatWebsiteHeader.tsx
> +    maxHeight: 40,
don't set heights here, do it within the props component of the button so we have a consistent feel to all our buttons and not varying heights everywhere

2022-05-12 07:39 UTC, jaredhanson11 commented on modules/flok/src/components/retreat-website/RetreatWebsiteHeader.tsx
> +    lineHeight: "25px",
why are we setting lineheight instead of using the default typography line height?

2022-05-12 07:39 UTC, jaredhanson11 commented on modules/flok/src/components/retreat-website/RetreatWebsiteHeader.tsx
> +      textDecoration: "none",
can probably use the `underline` prop on the Link component instead of this. i may be wrong if this isn't supported by those different values you can have for underline though

2022-05-12 07:39 UTC, jaredhanson11 commented on modules/flok/src/components/retreat-website/RetreatWebsiteHeader.tsx
> +      fontSize: "130%",
don't love this. use body2 for smaller screensize and body1 for larger. we want consistent typography across our app -- if possible. if not possible then at least use the "rem" unit of measurement instead of 130%. looking into rem if you need

2022-05-12 07:39 UTC, jaredhanson11 commented on modules/flok/src/components/retreat-website/RetreatWebsiteHeader.tsx
> +      fontWeight: theme.typography.fontWeightBold,
my AppTypography component will accept the prop, `fontWeight`. There's a use case where AppTypography doesn't work and its' if you want something like 

`<Typography comonent={"span"}>....` the AppTypography component won't accept the component prop. if you dont need that prop then you can use AppTypography and set these values in props

2022-05-12 07:39 UTC, jaredhanson11 commented on modules/flok/src/components/retreat-website/RetreatWebsiteHeader.tsx
> +      marginLeft: "15%",
marginLeft 15% never makes sense. use theme.spacing. i'm not even sure what the % is based off, the entire component width? or ...? not sure but this doesn't make sense to me don't think it should be there. i think % in padding and margins are a big no no if i'm not mistaken. could be wrong, let me know if i'm wrong here but still not sure why we need it based on a %

2022-05-12 07:39 UTC, jaredhanson11 commented on modules/flok/src/components/retreat-website/RetreatWebsiteHeader.tsx
> +      href={`/retreats/${titleToNavigation(
AppRoutes.getPath.

I'm considering changing the path from 'retreats' to something else and this would break if i wanted to do that

2022-05-12 07:39 UTC, jaredhanson11 commented on modules/flok/src/components/retreat-website/RetreatWebsiteHeader.tsx
> +        page?.title === props.selectedPage
use `className={clsx(classes.navigationLink, page?.title === props.selectedPage ? classes.selectedPageClassNameHere : undefined)}` instead of inline styles. also you can set the underline prop to "always" instead of setting it via css.

2022-05-12 07:39 UTC, jaredhanson11 commented on modules/flok/src/components/retreat-website/RetreatWebsiteHeader.tsx
> +        page?.title === props.selectedPage
the underline prop would be `page?.title === props.selectedPage ? "always" : "never/hover"` to get the same logic you have here

2022-05-12 07:39 UTC, jaredhanson11 commented on modules/flok/src/components/retreat-website/WYSIWYGBlockEditor.tsx
> +    marginTop: 30,
theme.spacing

2022-05-12 07:39 UTC, jaredhanson11 commented on modules/flok/src/components/retreat-website/WYSIWYGBlockEditor.tsx
> +    padding: "1rem",
theme.spacing

a piece of advice, we need to be more consistent with the unit types we're using. idk why we use % some places, rem some places, px other places all for padding. unless there's a good reason for it, let's try to keep it theme.spacing as much as possible

2022-05-12 07:39 UTC, jaredhanson11 commented on modules/flok/src/components/retreat-website/WYSIWYGBlockEditor.tsx
> +    margin: "10px",
theme.spacing

2022-05-12 07:39 UTC, jaredhanson11 commented on modules/flok/src/components/retreat-website/WYSIWYGBlockEditor.tsx
> +    margin: "10px",
replace absolute padding/margin with theme.spacing on this entire file

2022-05-12 07:39 UTC, jaredhanson11 commented on modules/flok/src/components/retreat-website/WYSIWYGBlockEditor.tsx
> +    dispatch(getBlock(props.blockId))
does this need to be here? should be handled in the useAttendeeLandingPageBlock hook, right?

2022-05-12 07:39 UTC, jaredhanson11 commented on modules/flok/src/pages/CreateRetreatWebsite.tsx
> +    marginTop: theme.spacing(1),
probably makes sense to move this as paddingTop into the `classes.body`. or if you want space between each element do the 

`"& > :not(:first-child)": {marginTop: theme.spacing(1)}` in body for spacing between all its children (keep paddingTop if you also want spacing on the top a well

2022-05-12 07:39 UTC, jaredhanson11 commented on modules/flok/src/pages/CreateRetreatWebsite.tsx
> +    backgroundColor: "white",
change this to theme.palette.background.paper (i think). it's white right now but if wanted to switch the theme of our site then it'd properly update

2022-05-12 07:39 UTC, jaredhanson11 commented on modules/flok/src/pages/RetreatWebsite.tsx
> +    replaceDashes(pageName ?? "home")
define your functions before calling them

2022-05-12 07:39 UTC, jaredhanson11 commented on modules/flok/src/pages/RetreatWebsite.tsx
> +          style={{
don't use inline styles, use className

2022-05-12 07:39 UTC, jaredhanson11 commented on modules/flok/src/pages/RetreatWebsite.tsx
> +      margin: "1em 0",
why em not theme.spacing

2022-05-12 07:39 UTC, jaredhanson11 commented on modules/flok/src/pages/RetreatWebsite.tsx
> +      margin: "1em 0",
em margin

2022-05-12 07:39 UTC, jaredhanson11 commented on modules/flok/src/store/actions/retreat.tsx
> +      successMessage: "Website name updated",
this is bad. you have a patchWebsite endpoint set up. what happens when we add new values to update. i'd either just say successfully updated website, or pass in the "success message" as a function to patchWebsite if it's something that's important to change based on what the form is editing.

2022-05-12 07:39 UTC, jaredhanson11 commented on modules/flok/src/models/retreat.tsx
> +  website_id: number
notice where you're placing this prop. //retreat itinerary fields. it should be grouped with the attendee fields. i'm also going to ask we change the column name in the backend to be attendees_website_id so will have to update that here as well (and anywhere else that references "website_id")

2022-05-12 07:39 UTC, jaredhanson11 commented on modules/flok/src/pages/LandingPageGenerator.tsx
> +                <div style={{display: "flex"}}>
inline styles = bad. keep consistency, create a class. worst case if it's small enough and just one css value then just do <Box flex={true}/>. I h8 inline styles with the style component though. hard to read

2022-05-12 07:39 UTC, jaredhanson11 commented on modules/flok/src/pages/LandingPageGenerator.tsx
> +  function handleCloseDeleteModal() {
define functin before it's being used, see line 338

2022-05-12 07:39 UTC, jaredhanson11 commented on modules/flok/src/pages/LandingPageGenerator.tsx
> +  function handleCloseDeleteModal() {
also probably don't even need this as a function. just use an arrow function. in line 338 it should just be setDeleteModalOpen(false) instead of calling this fn.

if it gets to a point where there's other actions that you take on close, then yes define the function. but right now it's a one liner, might as well just call the setDeleteModalOpen(false) itself

2022-05-12 07:39 UTC, jaredhanson11 commented on modules/flok/src/pages/LandingPageGenerator.tsx
> +        onClose={handleCloseDeleteModal}
`() => setDeleteModalOpen(false)`

2022-05-12 07:39 UTC, jaredhanson11 commented on modules/flok/src/pages/LandingPageGenerator.tsx
> +import {
this component is going to become unmaintainable fast. we should break it into different components instead of having all the logic in one place. i'll let it slide for now, but in the future please try to break it down into more manageable chunks so we can maintain the code easier.

2022-05-13 14:23 UTC, abusel commented on modules/flok/src/Stack.tsx
> +                AppRoutes.getPath("LandingPageGeneratorConfig"),
I totally get what you are saying here but I tried it and for some reason it doesn't work

2022-05-13 14:28 UTC, abusel commented on modules/flok/src/components/retreat-website/EditPageForm.tsx
> +          disabled={disabledChange}
does it make sense to move inline if I am using it twice?

2022-05-13 14:29 UTC, abusel commented on modules/flok/package.json
> +    "immutable": "^4.0.0",
I need to go over the dependency stuff with you, I don't really know the best way to add dependencies

2022-05-13 14:56 UTC, abusel commented on modules/flok/src/components/retreat-website/RetreatWebsiteHeader.tsx
> +            <Button
I made this change and the change below (removing maxHeight), the maxHeight was me incorrectly fixing the stretch caused by the flexbox instead of setting alignItems: center in the flexbox, after fixing that and setting size to small this is what it looks like.  let me know if you think this is fine or if size=small is too small

<img width="1512" alt="Screen Shot 2022-05-13 at 10 53 01 AM" src="https://user-images.githubusercontent.com/41205015/168310747-18933bf3-b6be-4dfd-93cd-c504a1f12b04.png">

2022-05-13 15:24 UTC, abusel commented on modules/flok/src/components/retreat-website/RetreatWebsiteHeader.tsx
> +      fontWeight: theme.typography.fontWeightBold,
happy to make this change, but since its only for small screen size, I would have to use the isSmallScreen hook and give the prop its value in a ternary, is that fine?

2022-05-13 15:29 UTC, abusel commented on modules/flok/src/components/retreat-website/RetreatWebsiteHeader.tsx
> +      marginLeft: "15%",
I used width 70% and margin left 15% to center the button without centering its siblings (the nav links) within the navigation drawer for mobile.  ie (left side 15%, button 70%, right side 15%). is this bad practice, was not sure how else to ensure the button was centered within that navigation drawer while keeping the links left aligned

2022-05-13 15:46 UTC, abusel commented on modules/flok/src/components/retreat-website/WYSIWYGBlockEditor.tsx
> +    margin: "10px",
I replaced it in most of the places, but for some of them it didn't seem to make sense to me to replace it with theme.spacing as some of the spacing is not dependent on a theme, ie making sure the toolbar doesn't overlap with the header and positioning the save button in the bottom right.  Let me know if you want this changed further

2022-05-13 16:07 UTC, abusel commented on modules/flok/src/models/retreat.tsx
> +  website_id: number
For this, I didn't find any other attendee fields in this model, only lodging, flights, itinerary, intake, and other documents.  I added a comment above it in the same style as the rest to distinguish it from the itinerary links, let me know if you think I should put it under any of those other groups

2022-05-13 17:50 UTC, abusel commented on modules/flok/src/components/retreat-website/RetreatWebsiteHeader.tsx
> +            <Button
still work to be done

2022-05-17 01:35 UTC, jaredhanson11 approved these changes

2022-05-17 01:35 UTC, merged