added width to single column container so that it doesn't overlap
Summ-Technologies/flok pull request #162
Opened 2022-05-19 15:59 UTC by abusel

#### Linear 🎫 
https://linear.app/flok/issue/FLO-342

##### Description
Added width to single column container which fixes and ensures no overlap at any size

##### Demo
<img width="1512" alt="Screen Shot 2022-05-19 at 11 57 36 AM" src="https://user-images.githubusercontent.com/41205015/169345220-da4af290-8c5d-4b86-92b5-c64deebd5efb.png">

2022-05-22 03:49 UTC, jaredhanson11 commented
@abusel this change still doesn't fix the issue. We need a better solution here, see the following example. It looks fine with "May" because it's a month with few letters. December gives it issues still.

Maybe the solution is to show the month abbreviation instead of full month, but just switching the width down up by 5% isn't the fix here.

<img width="721" alt="image" src="https://user-images.githubusercontent.com/11789958/169677606-2f8299c5-2bbf-4bbd-b8df-8f3f2df091c5.png">

2022-05-22 03:50 UTC, jaredhanson11 requested changes
see comment on the thread for changes requested

2022-05-27 15:10 UTC, abusel commented
Now switched to only showing first three letters of the months in the flight card
<img width="1512" alt="Screen Shot 2022-05-27 at 11 09 46 AM" src="https://user-images.githubusercontent.com/41205015/170727749-5f5ecdf6-da29-4a0a-b608-2e6c39b822f0.png">

2022-05-29 02:49 UTC, jaredhanson11 commented
<img width="366" alt="image" src="https://user-images.githubusercontent.com/11789958/170849825-c3c16ef9-adb6-4d7b-9888-6698f12da8a8.png">

2022-05-29 02:53 UTC, jaredhanson11 commented
@abusel i don't love this because there's a lot of splitting by space and substrings etc. There should be a better way to do this with Intl.DatetimeFormatter.

For example, in other countries what if it's standard to do the Day first then month then day of week. This would probably break. That being said, I'm happy to make this PR merged for now, but next time if we're doing something like this come to me and we'll see if there's a better way to approach it. I'm worried this is prone to bugs, and we're thinking to "US" local in terms of the way that the dates are displayed, but that's why we use the Intl package so it's formatted properly across all countries.

2022-05-29 02:56 UTC, jaredhanson11 approved these changes
approved, but don't love

2022-05-29 02:56 UTC, merged