Flo 392 custom default styles for different with picker
Summ-Technologies/flok pull request #217
Opened 2022-08-12 20:30 UTC by abusel

#### Linear 🎫 
https://linear.app/flok/issue/FLO-392

##### Description
Color picker for default text, background, and primary color for attendee landing page generator

##### Demo
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/41205015/184439353-faeb4a24-a180-455a-8177-1dad6ce8fda1.png">

2022-08-17 22:43 UTC, jaredhanson11 reviewed
@abusel when i switch to this branch to run I get a compile error. This is really dangerous to open PR's that have compile errors as they will break our production app. Please make sure to double check these things more closely when reviewing PR's

2022-08-31 18:59 UTC, jaredhanson11 requested changes

2022-08-31 18:59 UTC, jaredhanson11 commented on modules/flok/src/components/attendee-site/AttendeeSiteThemeProvider.tsx
> +        main: website?.primary_color ?? "#4b51ff",
tldr; if we ever wanted to change these colors (not just this one but others that are defined in strings) we'd have to cmd+shift+f for all the times we use those strings. put them in constants if needed

2022-09-01 14:20 UTC, abusel commented on modules/flok/src/components/attendee-site/AttendeeSiteThemeProvider.tsx
> +      <CssBaseline />
I intentionally put it in although I am not entirely sure what it does, just without it the styling didn't seem to take effect and found resources saying that this would make it work.. Will look into it more now to actually understand what it does

2022-09-09 00:25 UTC, jaredhanson11 approved these changes

2022-09-09 00:25 UTC, merged